export const walletTypes = {
  GET_ALL_REQUESTED: '@wallets/GET_ALL_REQUESTED',
  GET_ALL_SUCCESS: '@wallets/GET_ALL_SUCCESS',
  GET_ALL_FAILURE: '@wallets/GET_ALL_FAILURE',

  DEPOSIT_REQUESTED: '@wallets/DEPOSIT_REQUESTED',
  DEPOSIT_SUCCESS: '@wallets/DEPOSIT_SUCCESS',
  DEPOSIT_FAILURE: '@wallets/DEPOSIT_FAILURE',

  EXCHANGE_REQUESTED: '@wallets/EXCHANGE_REQUESTED',
  EXCHANGE_SUCCESS: '@wallets/EXCHANGE_SUCCESS',
  EXCHANGE_FAILURE: '@wallets/EXCHANGE_FAILURE',
}
